# Generated by Django 5.2.7 on 2025-12-18 11:04

from django.db import migrations, models

mappings = [
    ('due', 'pending'),
    ('paid', 'complete'),
]

def rename_statuses(apps, schema_editor):
    Transaction = apps.get_model('payment', 'Transaction')
    for before, after in mappings:
        Transaction.objects.filter(payment_status=before).update(payment_status=after)

def reverse_rename_statuses(apps, schema_editor):
    Transaction = apps.get_model('payment', 'Transaction')
    for before, after in mappings:
        Transaction.objects.filter(payment_status=after).update(payment_status=before)

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='due', max_length=40),
        ),
        migrations.RunPython(rename_statuses, reverse_rename_statuses),
    ]
