# Generated by Django 5.2.7 on 2025-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=65),
        ),
    ]
