# Generated by Django 5.2.7 on 2025-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='price',
            field=models.DecimalField(decimal_places=30, max_digits=65),
        ),
    ]
