# Generated by Django 5.2.7 on 2025-10-15 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('racket', 'Racket'), ('ball', 'Ball'), ('gym', 'Gym Equipment'), ('apparel', 'Sports Apparel'), ('accessory', 'Accessory')], default='shoes', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pembeli', 'Pembeli'), ('penjual', 'Penjual')], max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
