# Generated by Django 5.2.7 on 2025-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('pembeli', 'Pembeli'), ('penjual', 'Penjual')], default='pembeli', max_length=10),
        ),
    ]
