# Generated by Django 5.2.7 on 2025-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True, db_column='Product Name', null=True)),
                ('old_price', models.FloatField(blank=True, db_column='Old Price', null=True)),
                ('special_price', models.FloatField(blank=True, db_column='Special Price', null=True)),
                ('discount_field', models.FloatField(blank=True, db_column='Discount %', null=True)),
                ('product', models.TextField(blank=True, db_column='Product', null=True)),
            ],
            options={
                'db_table': 'products_data',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Shoes'), ('hockey', 'Racket'), ('volleyball', 'Ball'), ('basketball', 'Gym Equipment'), ('badminton', 'Sports Apparel'), ('accessory', 'Accessory')], default='shoes', max_length=50),
        ),
    ]
