# Generated by Django 5.2.7 on 2025-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productsdata_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Shoes'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('accessory', 'Accessory')], default='shoes', max_length=50),
        ),
    ]
