# Generated by Django 5.2.7 on 2025-10-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsdata',
            options={'managed': False, 'ordering': ['data_id']},
        ),
    ]
