# Generated by Django 5.2.7 on 2025-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productsdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('accessory', 'Accessory')], default='shoes', max_length=50),
        ),
    ]
